name: Build and publish PyHeap UI Docker image
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    name: Build and publish PyHeap UI Docker image
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/ivanyu/pyheap-ui

      - uses: docker/login-action@v2
        name: Login to GitHub Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        name: Build and push
        with:
          push: ${{ github.event_name == 'push' }}
          context: "{{defaultContext}}:pyheap-ui"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
