name: Pull request and push to main checks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run_tests_pyheap:
    name: Run tests for PyHeap
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1

      - name: Install dependencies
        working-directory: ./pyheap
        run: poetry install --no-interaction --no-root

      - name: Check with Black
        working-directory: ./pyheap
        run: |
          poetry run black --check .

      - name: Run tests
        working-directory: ./pyheap
        run: |
          poetry run pytest -vv tests

      - name: Build distribution
        working-directory: ./pyheap
        run: |
          make clean dist

  build_pyheap:
    name: Build PyHeap distribution
    runs-on: ubuntu-latest
    needs: run_tests_pyheap
    steps:
      - uses: actions/checkout@v3

      - name: Build distribution
        working-directory: ./pyheap
        run: |
          make clean dist

  run_tests_pyheap_ui:
    name: Run tests for PyHeap UI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1

      - name: Install dependencies for PyHeap
        working-directory: ./pyheap-ui
        run: poetry install --no-interaction --no-root

      - name: Check with Black
        working-directory: ./pyheap-ui
        run: |
          poetry run black --check .

      - name: Run tests for PyHeap
        working-directory: ./pyheap-ui
        run: |
          poetry run pytest -vv tests

  build_and_publish_pyheap_ui_docker_image:
    name: Build and publish PyHeap UI Docker image
    runs-on: ubuntu-latest
    needs: run_tests_pyheap_ui
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/ivanyu/pyheap-ui

      - uses: docker/login-action@v2
        name: Login to GitHub Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        name: Build and push
        with:
          push: ${{ github.event_name == 'push' }}
          context: "{{defaultContext}}:pyheap-ui"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
