name: Pull request and push to main checks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    name: Run tests
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run unit tests
        run: |
          poetry run pytest -vv tests/unit

      - name: Run integration tests
        run: |
          poetry run pytest -vv tests/integration
